#theme: jekyll-theme-cayman

# Site settings
title: Marc Dumon Notes
email: dumon.marc@gmail.com
description: "My notes on AI, Probability, Ergodicity and all things interesting"
baseurl: ""
url: "http://marcdumon.github.io"
twitter_username: marcdumon
github_username:  marcdumon

# Build settings
future: true
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

plugins:
    - jekyll-seo-tag
    
    
# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: marcdumon-github-io
